// AUTO-GENERATED by scripts/gen-tokens.py from @field-ds/tokens. Do not edit by hand.
// Durations are in SECONDS, the unit Motion expects.

export const duration = {
  instant: 0.04,
  xs: 0.1,
  sm: 0.16,
  base: 0.2,
  recede: 0.18,
  emphasized: 0.22,
  lg: 0.26,
  xl: 0.32,
} as const;

export const delay = {
  stagger: 0.025,
  beat: 0.12,
} as const;

export const easing = {
  standard: [0.32, 0.72, 0, 1] as const,
  loft: [0.22, 1, 0.36, 1] as const,
  accelerate: [0.4, 0, 1, 1] as const,
  decelerate: [0, 0, 0.2, 1] as const,
  easeInOut: [0.6, 0, 0.4, 1] as const,
} as const;
