#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# NOT needed to run this prototype. Its output (src/icons/icons.ts)
# is committed on purpose, so the package is standalone and needs no access to
# the Field design-system repo.
#
# This script only exists to REGENERATE that output after a DS bump. The RAW/SRC
# path below is an absolute path into a local checkout of the Field DS that will
# not exist on another machine — repoint it at your own checkout before running.
# ---------------------------------------------------------------------------
"""Pull the icon subset this prototype uses out of @field-ds/icons into one TS module.

Source of truth is the DS repo. Add a name to NEEDED and re-run:
    python3 scripts/gen-icons.py
"""
import re, pathlib

SRC = pathlib.Path("/Users/ssrawat/claude/.field_repo/field-design-system-main/packages/icons/src/svg")
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/icons/icons.ts"

NEEDED = [
    "system-language-bold", "system-language", "system-camera", "system-chevron-left", "system-chevron-down",
    "system-chevron-right", "system-search", "system-heart", "system-heart-filled", "system-plus", "system-star-filled",
    "system-arrow-down-circle-filled", "system-preferences", "system-sort", "system-discount",
    "system-discount-tag", "system-cross", "system-mic",
    "bottomnav-home-filled", "bottomnav-categories", "bottomnav-deals", "bottomnav-profile",
    "bottomnav-cart",
]

INNER = re.compile(r"<svg[^>]*>(.*)</svg>", re.S)
VIEWBOX = re.compile(r'viewBox="([^"]+)"')

entries = []
for name in NEEDED:
    raw = (SRC / f"{name}.svg").read_text()
    body = INNER.search(raw).group(1).strip()
    # The DS ships hardcoded ink; swap it so the icon inherits colour from CSS.
    body = re.sub(r'(fill|stroke)="#[0-9A-Fa-f]{3,8}"', r'\1="currentColor"', body)
    body = re.sub(r"\s+", " ", body)
    entries.append(f'  "{name}": {{ viewBox: "{VIEWBOX.search(raw).group(1)}", body: `{body}` }},')

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// AUTO-GENERATED by scripts/gen-icons.py from @field-ds/icons. Do not edit by hand.\n"
    "export type IconName =\n"
    + "\n".join(f'  | "{n}"' for n in NEEDED)
    + ";\n\nexport const icons: Record<IconName, { viewBox: string; body: string }> = {\n"
    + "\n".join(entries)
    + "\n};\n"
)
print(f"wrote {OUT} ({len(NEEDED)} icons)")
