#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# NOT needed to run this prototype. Its output (src/styles/tokens.css and src/motion/tokens.ts)
# is committed on purpose, so the package is standalone and needs no access to
# the Field design-system repo.
#
# This script only exists to REGENERATE that output after a DS bump. The RAW/SRC
# path below is an absolute path into a local checkout of the Field DS that will
# not exist on another machine — repoint it at your own checkout before running.
# ---------------------------------------------------------------------------
"""Flatten the Field DS token JSON (DTCG) into CSS custom properties + type classes.

Source of truth is the DS repo, not this file — re-run after a DS bump:
    python3 scripts/gen-tokens.py
"""
import json, re, pathlib, sys

RAW = pathlib.Path("/Users/ssrawat/claude/.field_repo/field-design-system-main/packages/tokens/src/raw")
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/styles/tokens.css"

def load(name):
    return json.loads((RAW / name).read_text())

base, semantic, text = load("base.json"), load("semantic.json"), load("text-styles.json")
tree = {**base, **semantic}

def walk(node, path=()):
    """Yield (dotted-path, $value) for every leaf token."""
    if isinstance(node, dict):
        if "$value" in node:
            yield ".".join(path), node["$value"]
            return
        for k, v in node.items():
            yield from walk(v, path + (k,))

flat = dict(walk(tree))

REF = re.compile(r"\{([^}]+)\}")

def resolve(value, depth=0):
    if depth > 12 or not isinstance(value, str):
        return value
    m = REF.fullmatch(value.strip())
    if m:
        return resolve(flat.get(m.group(1), value), depth + 1)
    return REF.sub(lambda mm: str(resolve(flat.get(mm.group(1), mm.group(0)), depth + 1)), value)

def varname(path):
    return "--" + path.replace(".", "-").replace("_", "-").lower()

lines = [
    "/* AUTO-GENERATED by scripts/gen-tokens.py from @field-ds/tokens. Do not edit by hand. */",
    ":root {",
]
for path, value in flat.items():
    v = resolve(value)
    if isinstance(v, list):                      # cubic-bezier easing
        v = "cubic-bezier(%s)" % ", ".join(str(n) for n in v)
    if isinstance(v, dict):                      # composite (typography) — emitted as classes below
        continue
    if isinstance(v, (int, float)) and not path.startswith(("base.font.weight", "font.weight")):
        v = f"{v}px"
    lines.append(f"  {varname(path)}: {v};")
lines.append("}")

# Typography composites -> utility classes (.t-B14-Regular etc.)
# The DS keeps the weight in `fontWeight`, as a name ("Medium"), not a number.
FAMILY = {
    "Noontree-Regular": 400, "Noontree-Medium": 500, "Noontree-SemiBold": 600,
    "Noontree-Bold": 700, "Noontree-ExtraBold": 800,
}
WEIGHT = {
    "Light": 300, "Regular": 400, "Medium": 500, "SemiBold": 600,
    "Bold": 700, "ExtraBold": 800, "Black": 900,
}
lines.append("")
for scale, weights in text.items():
    for weight, token in weights.items():
        v = token.get("$value", {})
        fam = resolve(v.get("fontFamily", ""))
        size = resolve(v.get("fontSize", ""))
        lh = resolve(v.get("lineHeight", ""))
        ls = resolve(v.get("letterSpacing", ""))
        fw = resolve(v.get("fontWeight", ""))
        num = lambda x: f"{x}px" if isinstance(x, (int, float)) else x
        lines += [
            f".t-{scale}-{weight} {{",
            f"  font-size: {num(size)};",
            f"  line-height: {num(lh)};",
            f"  letter-spacing: {num(ls)};",
            f"  font-weight: {WEIGHT.get(str(fw), FAMILY.get(fam, 400))};",
            "}",
        ]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} lines, {len(flat)} tokens)")

# The same motion tokens again as TS, because Motion wants seconds and arrays.
MOTION = OUT.parent.parent / "motion/tokens.ts"
ms = lambda p: float(str(resolve(flat[p])).replace("ms", "")) / 1000

durations = {k.split(".")[-1]: ms(k) for k in flat if k.startswith("motion.duration.")}
delays = {k.split(".")[-1]: ms(k) for k in flat if k.startswith("motion.delay.")}
easings = {k.split(".")[-1]: resolve(flat[k]) for k in flat if k.startswith("motion.easing.")}

MOTION.parent.mkdir(parents=True, exist_ok=True)
MOTION.write_text(
    "// AUTO-GENERATED by scripts/gen-tokens.py from @field-ds/tokens. Do not edit by hand.\n"
    "// Durations are in SECONDS, the unit Motion expects.\n\n"
    "export const duration = {\n"
    + "".join(f"  {k}: {v},\n" for k, v in durations.items())
    + "} as const;\n\nexport const delay = {\n"
    + "".join(f"  {k}: {v},\n" for k, v in delays.items())
    + "} as const;\n\nexport const easing = {\n"
    + "".join(f"  {k}: [{', '.join(str(n) for n in v)}] as const,\n" for k, v in easings.items())
    + "} as const;\n"
)
print(f"wrote {MOTION}")
